apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    # Exclude HTTPRoute from aserver-side apply.
    # See bug https://github.com/argoproj/argo-cd/issues/22151
    argocd.argoproj.io/sync-options: ServerSideApply=false
  name: ufo-httproute
spec:
  parentRefs:
  - name: ufo-gateway
    kind: Gateway
  # hostnames:
  # - "vybory.live"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: ufo-service
      port: 80
