apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    # Exclude HTTPRoute from aserver-side apply.
    # See bug https://github.com/argoproj/argo-cd/issues/22151
    argocd.argoproj.io/sync-options: ServerSideApply=false

  name: argocd-httproute
spec:
  parentRefs:
  - name: ufo-gateway
  # hostnames:
  # - "argocd.vybory.live"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-service
      port: 443
