resources:
  - argocd-httproute.yml

  - ufo/ufo-deployment.yml
  - ufo/ufo-migrate-job.yml
  - ufo/ufo-httproute.yml
  - ufo/ufo-service.yml

images:
 - name: ufo-image
   newName: registry.hub.docker.com/fak3/ufo
   newTag: "0.6"
