apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-kind-ufo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/spbelect/elect_hotline_deploy.git
    path: dev-kind
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: ufo-ns

  syncPolicy:
    syncOptions:
    # Some prometheus resources are too big for client-side. Use server-side.
    - ServerSideApply=true
