apiVersion: argoproj.io/v1alpha1
kind: Application
project: default
source:
  repoURL: https://github.com/spbelect/elect_hotline_deploy.git
  path: dev-kind
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: ufo-ns
