# Set HTTPRoute hostnames to {service}.kind to access on locallhost.
# Add to your /etc/hosts:
# 172.20.0.2 argocd.kind
# 172.20.0.2 prometheus.kind
# 172.20.0.2 grafana.kind
# 172.20.0.2 ufo.kind
# Where 172.20.0.2 is an ip of your local kind node which can be retrieved via
# > kubectl get node -o wide
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-httproute
spec:
  hostnames:
  - "grafana.kind"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-httproute
spec:
  hostnames:
  - "argocd.kind"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ufo-httproute
spec:
  hostnames:
  - "ufo.kind"
