resources:
  - ../base/

components:
  - ../base/metrics/grafana/
  - ../base/postgres/
  - ../base/gateway-api/
  - ../base/cert-manager/

patches:
  - path: nodeport.yml
  - path: httproute.yml
  - path: gateway.yml

  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: self-cert
      spec:
        dnsNames:
          - kind

  # debug logging for gateway
  - patch: |-
      apiVersion: gateway.nginx.org/v1alpha1
      kind: NginxGateway
      metadata:
        name: nginx-gateway-config
        namespace: nginx-gateway
      spec:
        logging:
          level: debug
