resources:
  - ../base/

components:
  - ../base/metrics/grafana/
  - ../base/postgres/
  - ../base/gateway-api/
  - ../base/cert-manager/

patches:
  - path: nodeport.yml
  - path: httproute.yml
  - path: gateway.yml

  # - patch: |-
  #     apiVersion: gateway.networking.k8s.io/v1
  #     kind: Gateway
  #     metadata:
  #       name: ufo-gateway
  #     spec:
  #       listeners:
  #       - protocol: HTTP
  #         name: ufo-http
  #         port: 80
  #
  #       - protocol: HTTPS
  #         name: ufo-https
  #         port: 443
  #         tls:
  #           mode: Terminate
  #           certificateRefs:
  #           - kind: Secret
  #             group: ""
  #             name: self-cert-secret
  #             # name: lets-staging-cert-secret
  #             # name: lets-cert-secret
